# yaml-language-server: $schema=https://json.schemastore.org/github-funding.json

# These are supported funding model platforms

github: riipandi # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
custom: []
