# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  pgsql:
    image: postgres:${PGSQL_VERSION:-17-alpine}
    container_name: myorg_pgsql
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgsql_data:/var/lib/postgresql/data
      - ./scripts/pgsql-multidb.sh:/docker-entrypoint-initdb.d/multidb.sh
    environment:
      POSTGRES_DB: myorg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securedb
      POSTGRES_EXTRA_DB: extradb1,extradb2
      POSTGRES_SCHEMAS: myorg:internal,extradb1:analytics
    command: ['postgres', '-c', 'wal_level=logical']
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d myorg']
      interval: 30s
      timeout: 20s
      retries: 3

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: myorg_pgweb
    restart: always
    ports:
      - 54321:8081
    environment:
      PGWEB_DATABASE_URL: 'postgres://postgres:securedb@pgsql:5432/myorg?sslmode=disable'
    depends_on:
      pgsql:
        condition: service_started

  mailpit:
    image: axllent/mailpit:latest
    container_name: myorg_mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 1025:1025 # port the SMTP server should be accessible on
      - 8025:8025 # port the web interface should be accessible on
    environment:
      # https://github.com/axllent/mailpit/wiki/Runtime-options
      # MP_UI_AUTH: 'user1:password1 user2:password2'
      TZ: Asia/Jakarta

  # ALLOW_EMPTY_PASSWORD is recommended only for development.
  # For better performance, consider `host` mode instead `port` to avoid docker NAT.
  # Notice: Docker `host` mode is NOT currently supported in Swarm Mode.
  # @ref: https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
  valkey:
    image: valkey/valkey:8-alpine
    container_name: myorg_valkey
    hostname: valkey
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    # network_mode: "host"
    volumes:
      - valkey_data:/data:rw
      # - ../scripts/valkey.conf:/etc/valkey.conf:ro
    # command: 'valkey-server /etc/valkey.conf --server-threads 2'
    ulimits:
      memlock: -1
      nofile:
        soft: 262144
        hard: 262144

volumes:
  pgsql_data:
    driver: local
  mailpit_data:
    driver: local
  valkey_data:
    driver: local
