# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  pgsql:
    image: postgres:17-alpine
    container_name: remix_pgsql
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgsql_data:/var/lib/postgresql/data
      - ./scripts/pgsql-multidb.sh:/docker-entrypoint-initdb.d/multidb.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securedb
      POSTGRES_DATABASES: remixdb,extradb
    command: ['postgres', '-c', 'wal_level=logical']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d remixdb']
      interval: 30s
      timeout: 20s
      retries: 3

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: remix_pgweb
    restart: always
    ports:
      - 54321:8081
    environment:
      PGWEB_DATABASE_URL: 'postgres://postgres:securedb@pgsql:5432/remixdb?sslmode=disable'
    depends_on:
      pgsql:
        condition: service_started

  mailpit:
    image: axllent/mailpit:latest
    container_name: remix_mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 1025:1025 # port the SMTP server should be accessible on
      - 8025:8025 # port the web interface should be accessible on
    environment:
      # https://github.com/axllent/mailpit/wiki/Runtime-options
      # MP_UI_AUTH: 'user1:password1 user2:password2'
      TZ: Asia/Jakarta

  valkey:
    image: valkey/valkey:8-bookworm
    container_name: remix_valkey
    hostname: valkey
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/data:rw
      # - ./scripts/valkey.conf:/etc/valkey.conf:ro
    # command: 'valkey-server /etc/valkey.conf --server-threads 2'

volumes:
  pgsql_data:
    driver: local
  mailpit_data:
    driver: local
  valkey_data:
    driver: local
